name: dest_os_ares_tablet_launcher

description: DEST-OS ARES sabit tablet ana ekran launcher projesi.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^7.1.1
  connectivity_plus: ^7.3.1
  geolocator: ^14.0.3
  http: ^1.6.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
